### ISSUE TITLE
Cannot use this library with vite

### ISSUE THREAD

**Issue by briot** [grvctr/tanstack-table-export-to-csv#2]
I just did `npm install ...` and then vite started complaining with
```
[w:]   ✘ [ERROR] Failed to resolve entry for package "tanstack-table-export-to-csv". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-scan]
[w:]
[w:]     node_modules/esbuild/lib/main.js:1374:21:
[w:]       1374 │         let result = await callback({
[w:]            ╵                      ^
[w:]
```

Fixing package.json to indicate the "main" is "index.js" instead of "index.ts" (which doesn't exist) seems to fix the issue.

regards
Emmanuel

**Comment by grvctr** [comment]
@briot 
Fixed
Try again

**Comment by briot** [comment]
Thanks.  I did experiment before I created this issue by modifying the file directly in node_modules/, so it works indeed.

**Comment by grvctr** [comment]
Thank you too!
